### ISSUE TITLE
MultiplayerSample Project needs to update its reference to the Multiplayer Gem jinja templates

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de-multiplayersample#44]
The Multiplayer Sample contains a reference to jinja template files within the Multiplayer Gem that are not available in an SDK layout build.
 The [multiplayersample_autogen_files.cmake](https://github.com/o3de/o3de-multiplayersample/blob/development/Gem/Code/multiplayersample_autogen_files.cmake) is referencing jinja template files from the Engine Source, which doesn't get copied to the Install SDK layout due to being in a private directory.

Furthermore that cmake file hardcodes the directory of the Multiplayer Gem location to be `${LY_ROOT_FOLDER}/Gems/Multiplayer` which isn't portable and would cause the MultiplayerSample project to fail to configure if the Multiplayer Gem was relocated outside of the Engine Source Repo or the folder was renamed.

Instead what should be done is to access the source directory of the Multiplayer Gem, that way the Multiplayer Gem can be relocated without breaking the Multiplayer Sample project
Running the `get_property(multiplayer_gem_source_dir TARGET Multiplayer PROPERTY SOURCE_DIR)` command can be used to lookup the source directory without using a generator expression

**Comment by Shatur** [comment]
> Instead what should be used is a generator expression that can access the source directory of the Multiplayer Gem, that way the Multiplayer Gem can be relocated without breaking the Multiplayer Sample project

But generator expressions are not expanded when assigned to a variable.
I have the following error in my project with the suggested approach:

```
CMake Error at D:/Programs/Windows/o3de-install/cmake/FileUtil.cmake:34 (message):
  File
  D:/Git/gardum/Code/$<TARGET_PROPERTY:Multiplayer,SOURCE_DIR>/Code/Source/AutoGen/AutoComponent_Common.jinja
  referenced in gardum_autogen_files.cmake not found
Call Stack (most recent call first):
  D:/Programs/Windows/o3de-install/cmake/LYWrappers.cmake:102 (ly_include_cmake_file_list)
  Code/CMakeLists.txt:23 (ly_add_target)
```

**Comment by lumberyard-employee-dm** [comment]
> > Instead what should be used is a generator expression that can access the source directory of the Multiplayer Gem, that way the Multiplayer Gem can be relocated without breaking the Multiplayer Sample project
> 
> But generator expressions are not expanded when assigned to a variable.
> I have the following error in my project with the suggested approach:
> 
> ```
> CMake Error at D:/Programs/Windows/o3de-install/cmake/FileUtil.cmake:34 (message):
>   File
>   D:/Git/gardum/Code/$<TARGET_PROPERTY:Multiplayer,SOURCE_DIR>/Code/Source/AutoGen/AutoComponent_Common.jinja
>   referenced in gardum_autogen_files.cmake not found
> Call Stack (most recent call first):
>   D:/Programs/Windows/o3de-install/cmake/LYWrappers.cmake:102 (ly_include_cmake_file_list)
>   Code/CMakeLists.txt:23 (ly_add_target)
> ```

Sounds like we would have to go with an alternative call to `get_property(multiplayer_gem_source_dir TARGET Multiplayer PROPERTY SOURCE_DIR)` which will read the target property from the Multiplayer target without needing to go through a generator expression

**Comment by Shatur** [comment]
> Sounds like we would have to go with an alternative call to get_property(multiplayer_gem_source_dir TARGET Multiplayer PROPERTY SOURCE_DIR)

Maybe put this files into a variable in Multiplayer gem to reference them in projects? Just to simplify things.

**Comment by lmbr-pip** [comment]
This maybe have been fixed by sig-platform. @amznestebanpapp was this fixed?

**Comment by amznestebanpapp** [comment]
@lmbr-pip partially, we are installing `.jinja` files, but they need to be in a `PUBLIC` include directory, in this case, those files are part of the `Source` folder which is private to that target, therefore they are not part of the "interface" of that target.
If those files are meant to be part of the interface, they should be in `Include`

Then there is a second part on how to refer to them, `${LY_ROOT_FOLDER}/Gems/Multiplayer` works for the SDK just because we purposely kept the same folder structure, but its not a good way to do that, imagine that Gem is not coming from the SDK or is in a different folder. Using `get_property(multiplayer_gem_source_dir TARGET Multiplayer PROPERTY SOURCE_DIR)` to get the folder is a step forward, but here the intention is also to treat the `.jinja` file as it was a "header" file. LyAutoGen doesnt have "include paths", so that should also be added in the future to support it. The goal would be that you depend on the Multiplayer target and get the public `.jinja` files of it accessible by referring to them directly, like:
```
Multiplayer/AutoGen/AutoComponent_Common.jinja
```

**Comment by lmbr-pip** [comment]
Believe this has been fixed for the Multiplayer Gem. Still needs to be fixed for Multiplayer Sample.

**Comment by lionants02** [comment]
![image](https://user-images.githubusercontent.com/5077672/169700867-bd298395-5168-4971-bf42-242a73987263.png)
Because my C:\ is small. I have migrated to E:\o3de.
I test it commit: a95beb2a5f7b86700659d8e25b4d5125fc6b0807
O3DE tag https://github.com/o3de/o3de/releases/tag/2205.0

Work for me.
I'm fine, no error found.

Build log.
<details>
<summary>Click view build log</summary>
<p>

```log
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30145.0
-- The CXX compiler identification is MSVC 19.29.30145.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: I:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: I:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using package E:/o3de/.o3de/3rdParty/packages/zlib-1.2.11-rev5-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/qt-5.15.2-rev7-windows
-- Using package E:/o3de/install/python/runtime/python-3.7.12-rev2-windows
-- Using Python 3.7.12 at E:/o3de/install/python/runtime/python-3.7.12-rev2-windows/python/python.exe
-- Python: Getting/Checking packages listed in E:/o3de/install/python/requirements.txt
-- Python: Getting/Checking packages listed in E:/o3de/install/python/requirements.txt - Already up to date.
-- Python: linking E:/o3de/install/scripts/o3de into python site-packages...
-- Using package E:/o3de/.o3de/3rdParty/packages/RapidJSON-1.1.0-rev1-multiplatform
-- Using package E:/o3de/.o3de/3rdParty/packages/Lua-5.4.4-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/RapidXML-1.13-rev1-multiplatform
-- Using package E:/o3de/.o3de/3rdParty/packages/zstd-1.35-multiplatform
-- Using package E:/o3de/.o3de/3rdParty/packages/cityhash-1.1-multiplatform
-- Using package E:/o3de/.o3de/3rdParty/packages/googletest-1.8.1-rev4-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/googlebenchmark-1.5.0-rev2-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/lz4-1.9.3-vcpkg-rev4-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/SQLite-3.37.2-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/OpenSSL-1.1.1m-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/expat-2.4.2-rev2-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/md5-2.0-multiplatform
-- Using package E:/o3de/.o3de/3rdParty/packages/tiff-4.2.0.15-rev3-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/squish-ccr-deb557d-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/assimp-5.1.6-rev1-windows
-- Python: linking E:/o3de/.o3de/3rdParty/packages/assimp-5.1.6-rev1-windows/assimp/port/PyAssimp into python site-packages...
-- Using package E:/o3de/.o3de/3rdParty/packages/xxhash-0.7.4-rev1-multiplatform
-- Using package E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/Crashpad-0.8.0-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/pybind11-2.4.3-rev3-multiplatform
-- Using Wwise SDK at E:\Program Files (x86)\Audiokinetic\Wwise 2021.1.8.7831
-- Using package E:/o3de/.o3de/3rdParty/packages/d3dx12-headers-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/vulkan-validationlayers-1.2.198-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/mcpp-2.7.2_az.2-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/DirectXShaderCompilerDxc-1.6.2112-o3de-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/SPIRVCross-2021.04.29-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/azslc-1.7.35-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/astc-encoder-3.2-rev2-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/ISPCTexComp-36b80aa-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/OpenEXR-3.1.3-rev2-windows
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Using package E:/o3de/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows
-- Found OpenGL: opengl32   
-- Using package E:/o3de/.o3de/3rdParty/packages/freetype-2.11.1-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/png-1.6.37-rev2-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/pyside2-qt-5.15.1-rev2-windows
-- Python: linking E:/o3de/.o3de/3rdParty/packages/pyside2-qt-5.15.1-rev2-windows/pyside2 into python site-packages...
-- Using package E:/o3de/.o3de/3rdParty/packages/AWSGameLiftServerSDK-3.4.2-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/poly2tri-7f0487a-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/v-hacd-2.3-1a49edf-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/civetweb-1.8-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/libsamplerate-0.2.1-rev2-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/NvCloth-v1.1.6-4-gd243404-pr58-rev1-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/mikkelsen-1.0.0.4-windows
-- Using package E:/o3de/.o3de/3rdParty/packages/OpenMesh-8.1-rev3-windows
-- Configuring done
-- Generating done
-- Build files have been written to: E:/o3de/Projects/o3de-multiplayersample/build/windows
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Running AutoGen for MultiplayerSample.Static
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkAiComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkAiComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkAnimationComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkAnimationComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkHealthComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkHealthComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkPlayerSpawnerComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkPlayerSpawnerComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkRandomComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkRandomComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkWeaponsComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkWeaponsComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkSimplePlayerCameraComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkSimplePlayerCameraComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkStressTestComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkStressTestComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkPlayerMovementComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkPlayerMovementComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkTestSpawnerComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkTestSpawnerComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkRandomImpulseComponent.AutoComponent.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkRandomImpulseComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkAiComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkAiComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkAnimationComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkAnimationComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkHealthComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkHealthComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkPlayerSpawnerComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkPlayerSpawnerComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkRandomComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkRandomComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkWeaponsComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkWeaponsComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkSimplePlayerCameraComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkSimplePlayerCameraComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkStressTestComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkStressTestComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkPlayerMovementComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkPlayerMovementComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkTestSpawnerComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkTestSpawnerComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\NetworkRandomImpulseComponent.AutoComponent.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkRandomImpulseComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\AutoComponentTypes.h using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponentTypes_Header.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkAiComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkAnimationComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkHealthComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkPlayerSpawnerComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkRandomComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkWeaponsComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkSimplePlayerCameraComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkStressTestComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkPlayerMovementComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkTestSpawnerComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkRandomImpulseComponent.AutoComponent.xml
  Generating E:\o3de\Projects\o3de-multiplayersample\build\windows\External\o3de-multiplayersample-0482897b\Gem\Code\Azcg\Generated\Source\AutoGen\AutoComponentTypes.cpp using template E:/o3de/install/Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponentTypes_Source.jinja and inputs E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkAiComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkAnimationComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkHealthComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkPlayerSpawnerComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkRandomComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkWeaponsComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkSimplePlayerCameraComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkStressTestComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkPlayerMovementComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkTestSpawnerComponent.AutoComponent.xml, E:\o3de\Projects\o3de-multiplayersample\Gem\Code\Source\AutoGen\NetworkRandomImpulseComponent.AutoComponent.xml
  Total Time 0:00:00.09
  Building Custom Rule E:/o3de/Projects/o3de-multiplayersample/Gem/Code/CMakeLists.txt
  unity_1_cxx.cxx
  unity_2_cxx.cxx
  unity_3_cxx.cxx
  unity_0_cxx.cxx
  unity_4_cxx.cxx
  MultiplayerSample.Static.vcxproj -> E:\o3de\Projects\o3de-multiplayersample\build\windows\lib\profile\MultiplayerSample.Static.lib
  Copying MultiplayerSample runtime dependencies to output...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./ImGui.imguilib.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./LmbrCentral.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysX_64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXCooking_64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXFoundation_64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXCommon_64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXDevice64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXGpu_64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  Building Custom Rule E:/o3de/Projects/o3de-multiplayersample/Gem/Code/CMakeLists.txt
  unity_0_cxx.cxx
     Creating library E:/o3de/Projects/o3de-multiplayersample/build/windows/lib/profile/MultiplayerSample.lib and object E:/o3de/Projects/o3de-multiplayersample/build/windows/lib/profile/MultiplayerSample.exp
  MultiplayerSample.vcxproj -> E:\o3de\Projects\o3de-multiplayersample\build\windows\bin\profile\MultiplayerSample.dll
  Copying MultiplayerSample.GameLauncher runtime dependencies to output...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-auth.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-cal.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-common.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-compression.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-event-stream.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-http.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-io.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-mqtt.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-s3.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-checksums.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-core.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-crt-cpp.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-dynamodb.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-lambda.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-s3.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./AWSCore.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./HttpRequestor.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-cognito-identity.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-cognito-idp.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-sts.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-identity-management.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./AWSClientAuth.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./AWSMetrics.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./AtomFont.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./AtomImGuiTools.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Atom_RHI_DX12.Private.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Atom_RHI_Null.Private.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/vulkan-validationlayers-1.2.198-rev1-windows/vulkan-validationlayers/lib/release/VkLayer_khronos_validation.json" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/vulkan-validationlayers-1.2.198-rev1-windows/vulkan-validationlayers/lib/release/VkLayer_khronos_validation.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Atom_RHI_Vulkan.Private.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Atom_Feature_Common.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Atom_RHI.Private.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Atom_RPI.Private.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./AtomLyIntegration_CommonFeatures.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./AtomViewportDisplayInfo.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Atom_Bootstrap.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Atom_Component_DebugCamera.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./EMotionFX.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./EMotionFX_Atom.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./ImguiAtom.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Atom_AtomBridge.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./GradientSignal.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./AudioSystem.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlast_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastExtAssetUtils_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastExtAuthoring_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastExtExporter_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastExtPhysX_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastExtPxSerialization_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastExtSerialization_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastExtShaders_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastExtStress_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastExtTkSerialization_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastGlobals_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/.o3de/3rdParty/packages/Blast-v1.1.7_rc2-9-geb169fe-rev2-windows/Blast/bin/vc15win64-cmake/profile/NvBlastTk_x64.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./PhysX.Gem.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Blast.Gem.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Camera.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./CameraFramework.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./CertificateManager.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./DebugDraw.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./ExpressionEvaluation.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./FastNoise.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./GameState.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Gestures.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./ImGui.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./CrySystem.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./LocalUser.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./TextureAtlas.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./LyShine.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Maestro.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Multiplayer.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Multiplayer.Debug.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./NvCloth.Gem.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./PhysXDebug.Gem.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Presence.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./SaveData.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./ScriptEvents.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./ScriptCanvas.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./ScriptCanvasPhysics.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./StartingPointInput.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./SurfaceData.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./Vegetation.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  -- Copying "E:/o3de/install/bin/Windows/profile/Default/./WhiteBox.dll" to "E:/o3de/Projects/o3de-multiplayersample/build/windows/bin/profile"...
  Building Custom Rule E:/o3de/install/CMakeLists.txt
  unity_0_cxx.cxx
     Creating library E:/o3de/Projects/o3de-multiplayersample/build/windows/lib/profile/MultiplayerSample.GameLauncher.lib and object E:/o3de/Projects/o3de-multiplayersample/build/windows/lib/profile/MultiplayerSample.GameLauncher.exp
  MultiplayerSample.GameLauncher.vcxproj -> E:\o3de\Projects\o3de-multiplayersample\build\windows\bin\profile\MultiplayerSample.GameLauncher.exe
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  MultiplayerSample.Static.vcxproj -> E:\o3de\Projects\o3de-multiplayersample\build\windows\lib\profile\MultiplayerSample.Static.lib
  MultiplayerSample.vcxproj -> E:\o3de\Projects\o3de-multiplayersample\build\windows\bin\profile\MultiplayerSample.dll
  Building Custom Rule E:/o3de/install/Code/Editor/CMakeLists.txt
```
</p>
</details>

**Comment by lumberyard-employee-dm** [comment]
Actually this isn't fixed. It is still hard coding the location of the Multiplayer Gem to be beneath the Engine root
The reference to the Multiplayer Gem in o3de in the [multiplayersample_autogen_files.cmake](https://github.com/o3de/o3de-multiplayersample/blob/development/Gem/Code/multiplayersample_autogen_files.cmake#L9-L13) needs to be updated to query the Multiplayer Gem Root using the `@GEMROOT:Multiplayer@` property.

The AutomatedTesting project autogen is an example of properly looking up the Multiplayer Gem location: https://github.com/o3de/o3de/blob/development/AutomatedTesting/Gem/Code/automatedtesting_autogen_files.cmake#L8-L16
